<?php
/*
 * Your installation or use of this SugarCRM file is subject to the applicable
 * terms available at
 * http://support.sugarcrm.com/Resources/Master_Subscription_Agreements/.
 * If you do not agree to all of the applicable terms or do not have the
 * authority to bind the entity as an authorized representative, then do not
 * install or use this SugarCRM file.
 *
 * Copyright (C) SugarCRM Inc. All rights reserved.
 */

// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
  'built_in_version' => '7.9.3.0',
  'acceptable_sugar_versions' => 
  array (
    0 => '',
  ),
  'acceptable_sugar_flavors' => 
  array (
    0 => 'PRO',
    1 => 'CORP',
    2 => 'ENT',
    3 => 'ULT',
  ),
  'readme' => '',
  'key' => 'TCT',
  'author' => 'Tactos',
  'description' => 'Módulo nuevo de Domicilios',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'Domicilios',
  'published_date' => '2018-01-11 04:27:23',
  'type' => 'module',
  'version' => 1515644843,
  'remove_tables' => 'prompt',
);


$installdefs = array (
  'id' => 'Domicilios',
  'beans' => 
  array (
    0 => 
    array (
      'module' => 'TCT_Sepomex',
      'class' => 'TCT_Sepomex',
      'path' => 'modules/TCT_Sepomex/TCT_Sepomex.php',
      'tab' => true,
    ),
    1 => 
    array (
      'module' => 'TCT_Domicilios',
      'class' => 'TCT_Domicilios',
      'path' => 'modules/TCT_Domicilios/TCT_Domicilios.php',
      'tab' => true,
    ),
    2 => 
    array (
      'module' => 'TCT_ZipCode',
      'class' => 'TCT_ZipCode',
      'path' => 'modules/TCT_ZipCode/TCT_ZipCode.php',
      'tab' => true,
    ),
  ),
  'layoutdefs' => 
  array (
  ),
  'relationships' => 
  array (
  ),
  'copy' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/modules/TCT_Sepomex',
      'to' => 'modules/TCT_Sepomex',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/modules/TCT_Domicilios',
      'to' => 'modules/TCT_Domicilios',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/modules/TCT_ZipCode',
      'to' => 'modules/TCT_ZipCode',
    ),
  ),
  'language' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/es_ES.lang.php',
      'to_module' => 'application',
      'language' => 'es_ES',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/en_us.lang.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
  ),
  'image_dir' => '<basepath>/icons',
);